# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
 branches:
   include:
     - '*'
 paths:
    include:
    - yamlTests/*
    exclude:
    - yamlTests/README.md

pool:
  vmImage: 'ubuntu-latest'




steps:
- task: Npm@1
  inputs:
    command: 'install'

- script: npm install yaml-validator

- script: const validator = new YamlValidator();

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
