# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "Azure OpenAPI"

trigger: none

variables:
  TRAVIS: 'true'
  TRAVIS_BRANCH: $(System.PullRequest.TargetBranch)
  TRAVIS_PULL_REQUEST: $(System.PullRequest.PullRequestNumber)
  TRAVIS_REPO_SLUG: $(Build.Repository.Name)
  TRAVIS_PULL_REQUEST_SLUG: $(Build.Repository.Name)
  TRAVIS_PULL_REQUEST_SHA: $(Build.SourceVersion)
  PR_ONLY: 'true'

jobs:
- template: .azure-pipelines/YamlFileValidetor.yaml
